// Code generated by protoc-gen-go.
// source: pb.proto
// DO NOT EDIT!

/*
Package ari_call is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	AllocateFdReq
	AllocateFdResp
	FreeFdReq
*/
package ari_call

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllocateFdReq struct {
	Db    string `protobuf:"bytes,1,opt,name=Db" json:"Db,omitempty"`
	Shard string `protobuf:"bytes,2,opt,name=Shard" json:"Shard,omitempty"`
}

func (m *AllocateFdReq) Reset()                    { *m = AllocateFdReq{} }
func (m *AllocateFdReq) String() string            { return proto.CompactTextString(m) }
func (*AllocateFdReq) ProtoMessage()               {}
func (*AllocateFdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllocateFdReq) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *AllocateFdReq) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

type AllocateFdResp struct {
	Db    string `protobuf:"bytes,1,opt,name=Db" json:"Db,omitempty"`
	Shard string `protobuf:"bytes,2,opt,name=Shard" json:"Shard,omitempty"`
	Fd    uint32 `protobuf:"varint,3,opt,name=Fd" json:"Fd,omitempty"`
}

func (m *AllocateFdResp) Reset()                    { *m = AllocateFdResp{} }
func (m *AllocateFdResp) String() string            { return proto.CompactTextString(m) }
func (*AllocateFdResp) ProtoMessage()               {}
func (*AllocateFdResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllocateFdResp) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *AllocateFdResp) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

func (m *AllocateFdResp) GetFd() uint32 {
	if m != nil {
		return m.Fd
	}
	return 0
}

type FreeFdReq struct {
	Db    string `protobuf:"bytes,1,opt,name=Db" json:"Db,omitempty"`
	Shard string `protobuf:"bytes,2,opt,name=Shard" json:"Shard,omitempty"`
	Fd    uint32 `protobuf:"varint,3,opt,name=Fd" json:"Fd,omitempty"`
}

func (m *FreeFdReq) Reset()                    { *m = FreeFdReq{} }
func (m *FreeFdReq) String() string            { return proto.CompactTextString(m) }
func (*FreeFdReq) ProtoMessage()               {}
func (*FreeFdReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FreeFdReq) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *FreeFdReq) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

func (m *FreeFdReq) GetFd() uint32 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func init() {
	proto.RegisterType((*AllocateFdReq)(nil), "ari_call.AllocateFdReq")
	proto.RegisterType((*AllocateFdResp)(nil), "ari_call.AllocateFdResp")
	proto.RegisterType((*FreeFdReq)(nil), "ari_call.FreeFdReq")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x48, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2c, 0xca, 0x8c, 0x4f, 0x4e, 0xcc, 0xc9, 0x51, 0x32,
	0xe5, 0xe2, 0x75, 0xcc, 0xc9, 0xc9, 0x4f, 0x4e, 0x2c, 0x49, 0x75, 0x4b, 0x09, 0x4a, 0x2d, 0x14,
	0xe2, 0xe3, 0x62, 0x72, 0x49, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x72, 0x49, 0x12,
	0x12, 0xe1, 0x62, 0x0d, 0xce, 0x48, 0x2c, 0x4a, 0x91, 0x60, 0x02, 0x0b, 0x41, 0x38, 0x4a, 0x6e,
	0x5c, 0x7c, 0xc8, 0xda, 0x8a, 0x0b, 0x88, 0xd3, 0x07, 0x52, 0xe5, 0x96, 0x22, 0xc1, 0xac, 0xc0,
	0xa8, 0xc1, 0x1b, 0xc4, 0xe4, 0x96, 0xa2, 0xe4, 0xc8, 0xc5, 0xe9, 0x56, 0x94, 0x4a, 0x8a, 0xd5,
	0xe8, 0x46, 0x24, 0xb1, 0x81, 0xbd, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x94, 0xe0, 0xc9,
	0xf7, 0xde, 0x00, 0x00, 0x00,
}
